### ISSUE TITLE
Possible to make it work for Redmine 3.4?

### ISSUE THREAD

**Issue by mauriziotallarico** [fraoustin/redmine_indicator#1] opened 2020-01-02 09:21 UTC
Hello, i've tried with Redmine 3.4 but rake is failing with the error: 

> NoMethodError: undefined method `[]' for #<ActiveRecord::Migration:0x97764fc>
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:664:in `block in method_missing'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `block in say_with_time'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:634:in `say_with_time'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:654:in `method_missing'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:416:in `method_missing'
> /var/www/redmine/plugins/redmine_indicator/db/migrate/20191221_indicator_custom_fields.rb:1:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.3.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /usr/local/rvm/gems/ruby-2.3.1/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `block in require'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:240:in `load_dependency'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activesupport-4.2.8/lib/active_support/dependencies.rb:274:in `require'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:777:in `load_migration'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:773:in `migration'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:768:in `disable_ddl_transaction'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:1051:in `use_transaction?'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:961:in `rescue in block in migrate'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:958:in `block in migrate'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `each'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:955:in `migrate'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:823:in `up'
> /usr/local/rvm/gems/ruby-2.3.1/gems/activerecord-4.2.8/lib/active_record/migration.rb:801:in `migrate'
> /var/www/redmine/lib/redmine/plugin.rb:481:in `migrate_plugin'
> /var/www/redmine/lib/redmine/plugin.rb:453:in `migrate'
> /var/www/redmine/lib/redmine/plugin.rb:467:in `block in migrate'
> /var/www/redmine/lib/redmine/plugin.rb:466:in `each'
> /var/www/redmine/lib/redmine/plugin.rb:466:in `migrate'
> /var/www/redmine/lib/tasks/redmine.rake:135:in `block (3 levels) in <top (required)>'
> /usr/local/rvm/gems/ruby-2.3.1/gems/rake-13.0.0/exe/rake:27:in `<top (required)>'
> /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
> /usr/local/rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

Thanks!

**Comment by fraoustin** [comment] 2020-01-02 13:43
Hi, thank you for your test

The problem is with the migrate script. You can create 3 Project Custom Fields:

- indicator_left_top
- indicator_left_bottom
- indicator_right

format: list
multiple: true
visible: false
value:
    - summary
    - opened_closed_today
    - opened_closed
    - opened_closed_10days
    - opened_closed_10weeks
    - spent_time_10days
    - spent_time_10weeks
    - by_priority
    - by_priority_all
    - by_status
    - by_status_all
    - by_tracker
    - by_tracker_all

I am looking for a compatible solution

**Comment by fraoustin** [comment] 2020-01-02 13:53
the new release 0.2.6 has a correction for the problem 
thank you

**Comment by fraoustin** [comment] 2020-01-05 07:13
It's ok for you? Can I close this issue?

**Comment by mauriziotallarico** [comment] 2020-01-05 08:04
Hi, sorry could not try yet. I'll be at work on 7th, I will try it and
feedback as soon as possible.
Thanks for your help.

Maurizio

Il dom 5 gen 2020, 08:13 fraoustin <notifications@github.com> ha scritto:

**Comment by mauriziotallarico** [comment] 2020-01-07 10:44
Hello,
migration works and plugin works now!
Many thanks for the prompt support, thumbs up!

**Closed as completed** 2020-01-07 11:42 UTC
